services:
  mongo:
    image: mongo:6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  gateway:
    build: ./gateway-service
    ports: ['3000:3000']
    env_file: .env
    depends_on: [mongo, auth, event]

  auth:
    build: ./auth-service
    ports: ['3001:3001']
    env_file: .env
    depends_on: [mongo]

  event:
    build: ./event-service
    ports: ['3002:3002']
    env_file: .env
    depends_on: [mongo]

volumes:
  mongo-data:
